### ISSUE TITLE
Logical OR operator support in SearchParameters

### ISSUE THREAD

**Issue by JinkiJung** [gla-rad/SECOMLib#1]
It seems to me that only AND operator is available in the [SECOM SearchParameters](https://github.com/gla-rad/SECOMLib/blob/master/secom-core/src/main/java/org/grad/secom/core/models/SearchParameters.java).

Can you update the model to support the OR operator or just correct me if I get it wrong?

Always appreciate your wonderful contribution! ❤️

**Comment by nvasta** [comment]
I think OR is also supported... For example try this in the freetext:

version:0.0.1 OR version:0.0.2

it's the NOT that is not supported currently. I will see if there is an easy way to introduce this.

**Comment by JinkiJung** [comment]
Thank you @nvasta for the answer. 

Now [I have corrected the query generator of the portal to use the freetext](https://github.com/maritimeconnectivity/ManagementPortal/pull/77), and it works nicely with OR!

**Comment by nvasta** [comment]
It seems that the NOT operation is kind of supported as well. For example you can search like that:

name:Service AND NOT version:0.1

However, the service will return nothing if you search for just: NOT version:0.1

It's kind of how the Lucene indexing works unfortunately, I don't completely understand it. I will try to look into it later on.

**Comment by nvasta** [comment]
It seems that you first need to select something that exists and then apply NOT for further filtering... weird...
